package com.matthewlim.ecommercewebapp.controllers;

import java.security.Principal;

import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.oauth2.client.authentication.OAuth2AuthenticationToken;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.matthewlim.ecommercewebapp.services.TokenService;

import lombok.AllArgsConstructor;

@AllArgsConstructor
@RestController
public class AuthController {

	private final TokenService tokenService;
	private final AuthenticationManager authenticationManager;
	
	@PostMapping("/login")
	public ResponseEntity<String> formLogin(@RequestParam("username") String username, @RequestParam("password") String password) {
		System.out.println("Login request received with username " + username + " and password " + password);
		Authentication authentication = authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(username, password));
		System.out.println("Form login authenticated using UsernamePasswordAuthenticationToken - Username: " + username + ", Password: " + password);
		String jwtToken = tokenService.generateToken(authentication);
		System.out.println("JWT generated by token service: " + jwtToken);
		
		return ResponseEntity.ok(jwtToken);
	}
	
	@GetMapping("/login/oauth2/code/github")
	public ResponseEntity<String> oauth2Login(@RequestParam("code") String code, OAuth2AuthenticationToken authentication) {
		String jwtToken = tokenService.generateToken(authentication);
		
		return ResponseEntity.ok(jwtToken);
	}
	
	@GetMapping("/home")
	public String homePage(Principal principal) {
		if (principal != null) {
			return "Welcome home " + principal.getName() + "!";
		} else {
			return "Welcome home stranger!";
		}
	}

	@GetMapping("/")
	public String defaultHome() {
		return "This is the default home page";
	}
	
	@GetMapping("/secured")
	public String secureHome() {
		return "This is the secured home page";
	}
}