version: '3.8'

services:
    backend:
        build: ./backend
        container_name: backend_c
        ports:
            - "9001:9001"
        env_file:
            - ./.env
        environment:
            spring.datasource.url: jdbc:mysql://database:3306/ecommerce
        depends_on:
            database:
                condition: service_healthy
        volumes:
            - ./backend:/build

    database:
        image: mysql:8.0
        container_name: database_c
        ports:
            - "3307:3306"
        env_file:
            - ./.env
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 3s
            retries: 5

    frontend:
        build: ./frontend
        container_name: frontend_c
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        stdin_open: true
        tty: true