version: '1.0.0'

services:
    backend:
        build: ./backend
        container_name: backend_c
        ports:
            - "9001:9001"
        environment:
            - DATABASE_USERNAME=root
            - DATABASE_PASSWORD=password
            - CLIENT_ID=${CLIENT_ID}
            - CLIENT_SECRET=${CLIENT_SECRET}
            - REDIRECT_URI=http://localhost:3000/oauth/callback
        depends_on:
            - database
        volumes:
            - ./backend:/app

    database:
        image: mysql:8.0
        container_name: database_c
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=ecommerce
            - MYSQL_ROOT_PASSWORD=password

    frontend:
        build: ./frontend
        container_name: frontend_c
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        stdin_open: true
        tty: true