version: '3.8'

services:
    backend:
        build: ./backend
        container_name: backend_c
        ports:
            - "9001:9001"
        env_file:
            - ./backend/.env
        environment:
            - MYSQL_DATABASE=ecommerce
            - MYSQL_ROOT_PASSWORD=password
        depends_on:
            - database
        volumes:
            - ./backend:/build

    database:
        image: mysql:8.0
        container_name: database_c
        ports:
            - "3307:3306"
        environment:
            - MYSQL_DATABASE=ecommerce
            - MYSQL_ROOT_PASSWORD=password

    frontend:
        build: ./frontend
        container_name: frontend_c
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        stdin_open: true
        tty: true